# Generated by Django 4.2.11 on 2024-04-19 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wishlist", "0001_initial"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="wishlist",
            field=models.ManyToManyField(related_name="users", to="wishlist.wishlist"),
        ),
    ]
