# Generated by Django 4.2.11 on 2024-04-23 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_alter_category_image"),
        ("order", "0003_alter_order_shipping_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="products",
            field=models.ManyToManyField(
                through="order.OrderItem", to="product.product"
            ),
        ),
    ]
