# Generated by Django 4.2.11 on 2024-04-23 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0004_order_products"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="products",
        ),
    ]
